### DISCUSSION TITLE
Texts when scrolling still visible. Thoughts?

### DISCUSSION THREAD

**Discussion by kfrichette** [iTwin/iTwinUI-react#170] [Q&A] [answered]
I set the position of my `<Header/>` to `fixed` since I want it stay on
 top of the page even when I'm scrolling.  But when I do scroll, texts are still visible.  Please see [codesandbox](https://codesandbox.io/s/header-format-5fw3p). Also saw it on my `<ExpandableBlock/>`.

Not sure if I'm missing some styling or this is an issue (that's why I didn't log a bug). Thoughts?

![header-fixed](https://user-images.githubusercontent.com/85319137/123486133-4f8cd980-d5c0-11eb-9df8-33ba9e906152.png)

Thank you!

**Comment by mayank99** [comment, marked as answer]
I think you just need to set `z-index` on the Header. It makes sense that elements that appear later in the DOM would otherwise show up above the Header.

`z-index: 1` is the minimum value I needed to make it work on your sandbox, but you might need a higher value in a real world app.

**Reply by mayank99** [reply]
Update: you may want to rethink the `position: fixed` approach as it creates a new [z-index stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context#:~:text=element%20with%20a%20position%20value%20fixed). This can cause problems with popover elements (such as dropdowns and tooltips) appearing below other elements. (I ran into this issue when building a layout)

I would recommend using flexbox or css grid, which don't require you to mess with z-indices or absolute positioning or margin hacks.

With flexbox, it can look like this:
```scss
body { margin: 0 } // reset browser-provided margin

.App {
  width: 100%;
  height: 100vh; // height of the viewport
  display: flex;
  flex-direction: column; 
}

.main-container { // sibling of header
  flex: 1;
  overflow: auto; // this makes the content scrollable, but not the header
}
```

If you also have sidenav and footer, grid is simpler: https://codesandbox.io/s/funny-khorana-vfble?file=/src/App.scss
